version: "3.7"

services:
  database_rentalx:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    env_file: .env
    container_name: rentalx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rentalx
    depends_on:
      - database_rentalx
volumes:
  pgdata:
    driver: local